name: nic_validator
description: A Flutter package to validate Sri Lankan National Identity Card (NIC) numbers. Supports both the new 12-digit format and the old 10-digit format (ending with V/X).

version: 0.1.1
homepage: 'https://github.com/msampathkumara/nic_validator'
repository: 'https://github.com/msampathkumara/nic_validator'

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

